# ===========================
# DATABASE CONNECTION
# ===========================
spring.datasource.url=jdbc:mysql://localhost:3306/auth_rbac_db
spring.datasource.username=root
spring.datasource.password=avanti25
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===========================
# JPA / HIBERNATE
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# JWT SECRET KEY
# ===========================
jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkey123456
jwt.expiration=86400000

# ===========================
# APP PORT
# ===========================
server.port=8080